version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - /path/to/prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
