version: '3'

services:
  grafana:
    image: grafana/grafana:8.0.5
    volumes:
      - /path/to/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
